import { registerPassthrough, registerLayouts, configureNunjucks } from "./config/basic-config.js";
import registerPostsCollection from "./config/collections/posts.js";
import registerTagListCollection from "./config/collections/tag-list.js";
import registerTagStatsCollection from "./config/collections/tag-stats.js";
import registerSassPlugin from "./config/plugins/sass.js";
import registerEsbuildPlugin from "./config/plugins/esbuild.js";
import registerImagePlugin from "./config/plugins/image.js";
import registerDateFilters from "./config/filters/dates.js";
import registerUrlFilters from "./config/filters/urls.js";
import registerSortingFilters from "./config/filters/sorting.js";
import registerTextFilters from "./config/filters/text.js";
import registerShortcodes from "./config/shortcodes.js";
import pluginTOC from "eleventy-plugin-nesting-toc";
import { lqipSvgTransform } from "./config/html-transform/lqip-svg-transform.js";
import { wrapPicturesTransform } from "./config/html-transform/wrap-pictures-transform.js";
import { fixAriaHiddenHeaderAnchorsTransform } from "./config/html-transform/fix-aria-hidden-header-anchors-transform.js";
import registerMarkdownPlugin from "./config/plugins/markdown.js";

export default async function (eleventyConfig) {
  // Passthrough copy rules
  registerPassthrough(eleventyConfig);

  // Collections
  registerPostsCollection(eleventyConfig);
  registerTagListCollection(eleventyConfig);
  registerTagStatsCollection(eleventyConfig);

  // Layout aliases
  registerLayouts(eleventyConfig);

  // Plugins
  registerSassPlugin(eleventyConfig);
  registerImagePlugin(eleventyConfig);
  registerEsbuildPlugin(eleventyConfig);
  await registerMarkdownPlugin(eleventyConfig);
  eleventyConfig.addPlugin(pluginTOC, {
    tags: ["h2", "h3", "h4"],
  });

  // Templating options
  configureNunjucks(eleventyConfig);

  // Filters
  registerDateFilters(eleventyConfig);
  registerUrlFilters(eleventyConfig);
  registerSortingFilters(eleventyConfig);
  registerTextFilters(eleventyConfig);

  //ShortCodes
  registerShortcodes(eleventyConfig);

  // Markdown configuration extracted to config/plugins/markdown.js

  eleventyConfig.addTransform("lqip-svg", lqipSvgTransform);

  // Wrap <picture> in a div.image-wrapper (run after LQIP transform)
  eleventyConfig.addTransform("wrap-pictures", wrapPicturesTransform);

  // Accessibility fix for heading permalink anchors generated by markdown-it-anchor.
  eleventyConfig.addTransform("fix-aria-hidden-header-anchors", fixAriaHiddenHeaderAnchorsTransform);

  // Rebuild when these files change in --serve mode
  eleventyConfig.addWatchTarget("./config/**/*.js");

  // CORS for giscus iframe for local development
  eleventyConfig.setServerOptions({
    headers: {
      "Access-Control-Allow-Origin": "https://giscus.app",
      "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
      "Cross-Origin-Resource-Policy": "cross-origin"
    },
    showAllHosts: true
  });

  return {
    dir: {
      input: "src", // Input directory
      includes: "_includes", // Includes directory (relative to input)
      output: "_site", // Output directory
    },
    markdownTemplateEngine: "njk", // Use Nunjucks for Markdown
    htmlTemplateEngine: "njk", // Use Nunjucks for HTML
    dataTemplateEngine: "njk",
  };
}
